# Site settings
title: JSWare.io
subtitle: "The pain of low quality far outlasts the joy of low price"

logo: "/assets/favicons/favicon-32x32.png"
teaser: "/assets/images/teaser.png"
repository: "jsware/jsware.github.io"

name: &me "John Scott"
email:
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: JohnScottUK
github_username: jsware
linkedin_username: JohnScottUK

url: &url "https://www.jsware.io"
baseurl: "" # the subpath of your site, e.g. /blog

minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: pretty
paginate: 8 
paginate_path: /page:num/
timezone: Europe/London

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - bin
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : *me
  avatar : "/assets/images/john.png"
  bio    : "The contents of this site are entirely my own and do not represent the views or opinions of my employer."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: *url
    - label: linkedin
      icon: "fab fa-fw fa-linkedin"
      url: &linkedin "https://linkedin.com/in/JohnScottUK"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: &github "https://github.com/JohnScottUK/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: &twitter "https://twitter.com/JohnScottUK"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: &instagram "https://www.instagram.com/jsware"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: *linkedin
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: *github
    - label: "JSWare"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jsware"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: *twitter
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: *instagram

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-29106762-2"
    anonymize_ip: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      show_date: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
